sudo: required

dist: bionic

language: python

python:

  - "3.8"

install: 

   - pip install pyang
   - pip install xym
   - pip install xml2rfc

script:

  - cd I-D-L3NM
  - xym draft-ietf-opsawg-l3sm-l3nm-04.txt
  - export yang_extracted=`ls *.yang`
  - xml2rfc draft-ietf-opsawg-l3sm-l3nm-04.xml
  - cd ..
  - cd yang
  - cd IETF-04
  - pyang -f tree --ietf ietf-l3vpn-ntw.yang
  - pyang -f tree --tree-print-groupings ietf-vpn-common.yang

 
