sudo: required

dist: bionic

language: python

python:

  - "3.8"

install: 

   - pip install pyang
   - pip install xym
   - pip install xml2rfc

script:

  - echo "Checking latest L3NM draft vs latest common in the repository"
  - cd I-D-L3NM
  - xml2rfc --legacy draft-ietf-opsawg-l3sm-l3nm.xml
  - xym draft-ietf-opsawg-l3sm-l3nm.txt
  - export yang_extracted=`ls *.yang`
  - cp ../yang/ietf-vpn-common.yang .
  - curl -o ietf-yang-types@2010-09-24.yang https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-yang-types@2010-09-24.yang
  - curl -o ietf-inet-types@2010-09-24.yang https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/standard/ietf/RFC/ietf-inet-types@2010-09-24.yang
  - pyang -f tree $yang_extracted
  - echo "Checking latest L2NM draft vs latest common in the repository"
  - cd ..
  - cd I-D-L2NM
  - xml2rfc --legacy draft-ietf-opsawg-l2nm.xml
  - xym draft-ietf-opsawg-l2nm.txt
  - export yang_extracted=`ls *.yang`
  - cp ../yang/ietf-vpn-common.yang .
  - curl -o ietf-yang-types@2010-09-24.yang https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-yang-types@2010-09-24.yang
  - curl -o ietf-inet-types@2010-09-24.yang https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/standard/ietf/RFC/ietf-inet-types@2010-09-24.yang
  - pyang -f tree $yang_extracted
  - echo "Checking latest L3NM and L2NM yang in the yang directory vs latest common in git"
  - cd ..
  - cd yang
  - pyang -f tree --ietf ietf-l3vpn-ntw.yang
  - pyang -f tree --ietf ietf-l2vpn-ntw.yang
  - pyang -f tree --tree-print-groupings ietf-vpn-common.yang

 
